-- Generated by Pumpkin

local data = {}

local path = ...
if type(path) ~= "string" then
	path = "."
end
data.image = love.graphics.newImage(path.."flower_d.png")
data.image:setFilter("nearest", "nearest")
data.animations = {
	flower_baby={
		[0]={u=98, v=0, w=16, h=34, offsetX=4, offsetY=32, duration=0.0333333},
		scale=1
	},
	flower_mature={
		[0]={u=0, v=0, w=62, h=104, offsetX=26, offsetY=100, duration=0.0333333},
		scale=1
	},
	flower_young={
		[0]={u=62, v=0, w=36, h=54, offsetX=16, offsetY=49, duration=0.0333333},
		scale=1
	},
}
data.quad = love.graphics.newQuad(0, 0, 1, 1, data.image:getWidth(), data.image:getHeight())

return data
