-- Generated by Pumpkin

local data = {}

local path = ...
if type(path) ~= "string" then
	path = "."
end
data.image = love.graphics.newImage(path.."blossom_c.png")
data.image:setFilter("nearest", "nearest")
data.animations = {
	blossom_baby={
		[0]={u=0, v=72, w=20, h=24, offsetX=6, offsetY=26, duration=0.0333333},
		scale=1
	},
	blossom_baby_cel={
		[0]={u=46, v=38, w=24, h=32, offsetX=8, offsetY=28, duration=0.0333333},
		scale=1
	},
	blossom_mature={
		[0]={u=0, v=38, w=46, h=34, offsetX=21, offsetY=30, duration=0.0333333},
		scale=1
	},
	blossom_mature_cel={
		[0]={u=0, v=0, w=52, h=38, offsetX=25, offsetY=32, duration=0.0333333},
		scale=1
	},
	blossom_young={
		[0]={u=88, v=0, w=34, h=28, offsetX=18, offsetY=27, duration=0.0333333},
		scale=1
	},
	blossom_young_cel={
		[0]={u=52, v=0, w=36, h=32, offsetX=18, offsetY=28, duration=0.0333333},
		scale=1
	},
}
data.quad = love.graphics.newQuad(0, 0, 1, 1, data.image:getWidth(), data.image:getHeight())

return data
