-- Generated by Pumpkin

local data = {}

local path = ...
if type(path) ~= "string" then
	path = "."
end
data.image = love.graphics.newImage(path.."blossom_a.png")
data.image:setFilter("nearest", "nearest")
data.animations = {
	blossom_baby={
		[0]={u=70, v=0, w=14, h=26, offsetX=6, offsetY=26, duration=0.0333333},
		scale=1
	},
	blossom_baby_cel={
		[0]={u=52, v=0, w=18, h=32, offsetX=8, offsetY=27, duration=0.0333333},
		scale=1
	},
	blossom_mature={
		[0]={u=40, v=48, w=48, h=38, offsetX=23, offsetY=39, duration=0.0333333},
		scale=1
	},
	blossom_mature_cel={
		[0]={u=0, v=0, w=52, h=48, offsetX=26, offsetY=40, duration=0.0333333},
		scale=1
	},
	blossom_young={
		[0]={u=88, v=0, w=34, h=36, offsetX=15, offsetY=35, duration=0.0333333},
		scale=1
	},
	blossom_young_cel={
		[0]={u=0, v=48, w=40, h=42, offsetX=18, offsetY=35, duration=0.0333333},
		scale=1
	},
}
data.quad = love.graphics.newQuad(0, 0, 1, 1, data.image:getWidth(), data.image:getHeight())

return data
