-- Generated by Pumpkin

local data = {}

local path = ...
if type(path) ~= "string" then
	path = "."
end
data.image = love.graphics.newImage(path.."bush_d.png")
data.image:setFilter("nearest", "nearest")
data.animations = {
	bush_baby={
		[0]={u=230, v=0, w=26, h=50, offsetX=16, offsetY=48, duration=0.0333333},
		scale=1
	},
	bush_mature={
		[0]={u=0, v=0, w=132, h=106, offsetX=74, offsetY=103, duration=0.0333333},
		scale=1
	},
	bush_young={
		[0]={u=132, v=0, w=98, h=66, offsetX=52, offsetY=62, duration=0.0333333},
		scale=1
	},
}
data.quad = love.graphics.newQuad(0, 0, 1, 1, data.image:getWidth(), data.image:getHeight())

return data
