-- Generated by Pumpkin

local data = {}

local path = ...
if type(path) ~= "string" then
	path = "."
end
data.image = love.graphics.newImage(path.."bush_a.png")
data.image:setFilter("nearest", "nearest")
data.animations = {
	bush_baby={
		[0]={u=98, v=120, w=52, h=54, offsetX=23, offsetY=46, duration=0.0333333},
		scale=1
	},
	bush_mature={
		[0]={u=0, v=0, w=168, h=120, offsetX=84, offsetY=113, duration=0.0333333},
		scale=1
	},
	bush_young={
		[0]={u=0, v=120, w=98, h=72, offsetX=51, offsetY=68, duration=0.0333333},
		scale=1
	},
}
data.quad = love.graphics.newQuad(0, 0, 1, 1, data.image:getWidth(), data.image:getHeight())

return data
