-- Generated by Pumpkin

local data = {}

local path = ...
if type(path) ~= "string" then
	path = "."
end
data.image = love.graphics.newImage(path.."bush_b.png")
data.image:setFilter("nearest", "nearest")
data.animations = {
	bush_baby={
		[0]={u=156, v=184, w=88, h=88, offsetX=39, offsetY=84, duration=0.0333333},
		scale=1
	},
	bush_mature={
		[0]={u=0, v=0, w=202, h=184, offsetX=118, offsetY=181, duration=0.0333333},
		scale=1
	},
	bush_young={
		[0]={u=0, v=184, w=156, h=126, offsetX=75, offsetY=123, duration=0.0333333},
		scale=1
	},
}
data.quad = love.graphics.newQuad(0, 0, 1, 1, data.image:getWidth(), data.image:getHeight())

return data
