-- Generated by Pumpkin

local data = {}

local path = ...
if type(path) ~= "string" then
	path = "."
end
data.image = love.graphics.newImage(path.."flower_e.png")
data.image:setFilter("nearest", "nearest")
data.animations = {
	flower_baby={
		[0]={u=110, v=0, w=10, h=30, offsetX=5, offsetY=28, duration=0.0333333},
		scale=1
	},
	flower_mature={
		[0]={u=0, v=0, w=66, h=110, offsetX=29, offsetY=107, duration=0.0333333},
		scale=1
	},
	flower_young={
		[0]={u=66, v=0, w=44, h=82, offsetX=18, offsetY=80, duration=0.0333333},
		scale=1
	},
}
data.quad = love.graphics.newQuad(0, 0, 1, 1, data.image:getWidth(), data.image:getHeight())

return data
