-- Generated by Pumpkin

local data = {}

local path = ...
if type(path) ~= "string" then
	path = "."
end
data.image = love.graphics.newImage(path.."flower_a.png")
data.image:setFilter("nearest", "nearest")
data.animations = {
	flower_baby={
		[0]={u=40, v=0, w=6, h=24, offsetX=3, offsetY=22, duration=0.0333333},
		[1]={u=40, v=0, w=6, h=24, offsetX=3, offsetY=22, duration=0.0333333},
		scale=1
	},
	flower_mature={
		[0]={u=0, v=0, w=30, h=84, offsetX=21, offsetY=80, duration=0.0333333},
		[1]={u=0, v=0, w=30, h=84, offsetX=21, offsetY=80, duration=0.0333333},
		scale=1
	},
	flower_young={
		[0]={u=30, v=0, w=10, h=52, offsetX=3, offsetY=48, duration=0.0333333},
		[1]={u=30, v=0, w=10, h=52, offsetX=3, offsetY=48, duration=0.0333333},
		scale=1
	},
}
data.quad = love.graphics.newQuad(0, 0, 1, 1, data.image:getWidth(), data.image:getHeight())

return data
