-- Generated by Pumpkin

local data = {}

local path = ...
if type(path) ~= "string" then
	path = "."
end
data.image = love.graphics.newImage(path.."flower_c.png")
data.image:setFilter("nearest", "nearest")
data.animations = {
	flower_baby={
		[0]={u=88, v=0, w=14, h=40, offsetX=8, offsetY=38, duration=0.0333333},
		scale=1
	},
	flower_mature={
		[0]={u=0, v=0, w=54, h=88, offsetX=12, offsetY=83, duration=0.0333333},
		scale=1
	},
	flower_young={
		[0]={u=54, v=0, w=34, h=68, offsetX=22, offsetY=65, duration=0.0333333},
		scale=1
	},
}
data.quad = love.graphics.newQuad(0, 0, 1, 1, data.image:getWidth(), data.image:getHeight())

return data
