-- Generated by Pumpkin

local data = {}

local path = ...
if type(path) ~= "string" then
	path = "."
end
data.image = love.graphics.newImage(path.."flower_b.png")
data.image:setFilter("nearest", "nearest")
data.animations = {
	flower_baby={
		[0]={u=52, v=64, w=18, h=34, offsetX=4, offsetY=32, duration=0.0333333},
		scale=1
	},
	flower_mature={
		[0]={u=0, v=0, w=52, h=106, offsetX=32, offsetY=100, duration=0.0333333},
		scale=1
	},
	flower_young={
		[0]={u=52, v=0, w=20, h=64, offsetX=13, offsetY=61, duration=0.0333333},
		scale=1
	},
}
data.quad = love.graphics.newQuad(0, 0, 1, 1, data.image:getWidth(), data.image:getHeight())

return data
