-- Generated by Pumpkin

local data = {}

local path = ...
if type(path) ~= "string" then
	path = "."
end
data.image = love.graphics.newImage(path.."tree_b.png")
data.image:setFilter("nearest", "nearest")
data.animations = {
	tree_baby={
		[0]={u=870, v=0, w=100, h=254, offsetX=49, offsetY=247, duration=0.0333333},
		scale=1
	},
	tree_mature={
		[0]={u=0, v=0, w=616, h=1360, offsetX=313, offsetY=1331, duration=0.0333333},
		scale=1
	},
	tree_young={
		[0]={u=616, v=0, w=254, h=528, offsetX=127, offsetY=510, duration=0.0333333},
		scale=1
	},
}
data.quad = love.graphics.newQuad(0, 0, 1, 1, data.image:getWidth(), data.image:getHeight())

return data
